#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/krakazyabra/microservices/tree/main/charts/common/values.yaml
#
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.19.0"
secret: {}
# See more environment variables in the template documentation
# https://template.org/docs
env: {}
# TZ: ""

service:
  port:
    port: 80
ingress:
  enabled: false
  hosts:
    - host: nginx.192.168.1.203.nip.io
persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config
